<a href="https://colab.research.google.com/github/pakianaconda/anaconda/blob/master/Prediction%20of%20full%20load%20electrical%20power%20output%20by%20ANN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Prediction of full load electrical power output of a base load operated combined cycle power plant using machine learning methods(ANN)

##### Attribute Information:

##### Features consist of hourly average ambient variables
##### - Temperature (T) in the range 1.81°C and 37.11°C,
##### - Ambient Pressure (AP) in the range 992.89-1033.30 milibar,
##### - Relative Humidity (RH) in the range 25.56% to 100.16%
##### - Exhaust Vacuum (V) in teh range 25.36-81.56 cm Hg
##### - Net hourly electrical energy output (EP) 420.26-495.76 MW
##### The averages are taken from various sensors located around the plant that  record the ambient variables every second. The variables are given without normalization

### Importing the libraries

In [ ]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [ ]:
tf.__version__

'2.9.2'

## Part 1 - Data Preprocessing

### Importing the dataset

In [ ]:
dataset = pd.read_excel('Folds5x2_pp.xlsx')
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [ ]:
dataset

AT      V       AP     RH      PE
0     14.96  41.76  1024.07  73.17  463.26
1     25.18  62.96  1020.04  59.08  444.37
2      5.11  39.40  1012.16  92.14  488.56
3     20.86  57.32  1010.24  76.64  446.48
4     10.82  37.50  1009.23  96.62  473.90
...     ...    ...      ...    ...     ...
9563  16.65  49.69  1014.01  91.00  460.03
9564  13.19  39.18  1023.67  66.78  469.62
9565  31.32  74.33  1012.92  36.48  429.57
9566  24.48  69.45  1013.86  62.39  435.74
9567  21.60  62.52  1017.23  67.87  453.28

[9568 rows x 5 columns]

In [ ]:
X

array([[  14.96,   41.76, 1024.07,   73.17],
       [  25.18,   62.96, 1020.04,   59.08],
       [   5.11,   39.4 , 1012.16,   92.14],
       ...,
       [  31.32,   74.33, 1012.92,   36.48],
       [  24.48,   69.45, 1013.86,   62.39],
       [  21.6 ,   62.52, 1017.23,   67.87]])

In [ ]:
y

array([463.26, 444.37, 488.56, ..., 429.57, 435.74, 453.28])

### Splitting the dataset into the Training set and Test set

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.15, random_state = 0)

## Part 2 - Building the ANN

### Initializing the ANN

In [ ]:
# We have to introduce it as a sequence of layer.
# So the way to do this is by creating an object of the sequential class by tensor flow.
# So as you understand tensor flow is like a deep learning library which allows you to build complex neural networks 
# and train them with tools like optimizer is or lost function or drop out tools.

# One of these classes is actually the sequential class which will exactly create an artificial new network initialized as a sequence of layers.

ann = tf.keras.models.Sequential()

### Adding the input layer and the first hidden layer

In [ ]:
# why is it call a dense class.
# 'Dense class' stands for actually the connection between the input layer and the first hidden layer.
# Because indeed as we can clearly see in this graphic well there is a full connection between the input -
# layer here and the first hidden layer meaning that all the neurons which are here the features are fully connected to 
# all the hidden neurons here of the first hidden layer.
# that's exactly what this dense class means. You can see the high density of the connections here.

ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

### Adding the second hidden layer

In [ ]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

### Adding the output layer

In [ ]:
# If you're doing classification with only two categories to predict in the end you know either yes or no, or, 0 or 1.
# Well you have to choose a sigmoid activation function if you're doing classification with more than two categories 
# or classes to predict in the end while you should use a soft-Max activation function.

# And if you're doing regression meaning that you have to predict a continuous real number as a final output 
# then you should choose no activation function.

In [ ]:
ann.add(tf.keras.layers.Dense(units=1))

## Part 3 - Training the ANN

### Compiling the ANN

In [ ]:
# First here we'll compile the ANZ meaning that we will connect it to an optimizer which will take care of reducing the loss 
# during backward propagation stochastic gradient descent 


# What is an optimizer and a lost function?

# The optimizer is basically the tool with which you're going to perform stochastic gradient descent.



# What is the stochastic gradient descent?

# That's a technique that consists of updating the weights of each of the neurons in the hidden layers 
# so as to reduce the loss over the epochs.In other words, what will happen is that first forward propagation will happen.
# You know, the features will be entered into the neural network.
# The signal will be forward, propagated up to the energy output.
# This energy output, meaning the prediction will be compared to the real energy output of the training set.You know, we have the real results.
# This will incur a loss, which will be exactly the squared difference between the predicted energy output and the real energy output.
# And usually the predictions come into batches so that we actually compute the sum of the squared differences between the predicted energy 
# output and the real energy outputs in the batch. So basically, you get a loss and then backward propagation is applied, meaning that this
# loss is back propagated into the neural network and stochastic gradient descent is applied with this optimizer to reduce the loss, 
#So basically the optimizer will update all the weights inside this new network in order to reduce this load. That was 
# backpropagated into the normal network.

ann.compile(optimizer = 'adam', loss = 'mean_squared_error')

### Training the ANN model on the Training set

In [ ]:
ann.fit(X_train, y_train, batch_size = 32, epochs = 72)

Epoch 1/72
255/255 [==============================] - 0s 2ms/step - loss: 26.2519
Epoch 2/72
255/255 [==============================] - 0s 2ms/step - loss: 26.1109
Epoch 3/72
255/255 [==============================] - 0s 2ms/step - loss: 26.3820
Epoch 4/72
255/255 [==============================] - 0s 2ms/step - loss: 26.2031
Epoch 5/72
255/255 [==============================] - 0s 2ms/step - loss: 26.2234
Epoch 6/72
255/255 [==============================] - 0s 2ms/step - loss: 26.0652
Epoch 7/72
255/255 [==============================] - 0s 2ms/step - loss: 26.7477
Epoch 8/72
255/255 [==============================] - 0s 2ms/step - loss: 26.3494
Epoch 9/72
255/255 [==============================] - 0s 2ms/step - loss: 26.2913
Epoch 10/72
255/255 [==============================] - 0s 2ms/step - loss: 26.4394
Epoch 11/72
255/255 [==============================] - 0s 2ms/step - loss: 26.1463
Epoch 12/72
255/255 [==============================] - 0s 2ms/step - loss: 26.5955
Epoch 13/72
2

### Predicting the results of the Test set

In [ ]:
y_pred = ann.predict(X_test)
np.set_printoptions(precision=2)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

45/45 [==============================] - 0s 1ms/step
[[431.32 431.23]
 [462.3  460.01]
 [465.78 461.14]
 ...
 [444.45 445.6 ]
 [454.48 451.7 ]
 [458.8  460.45]]
